# 78张标准塔罗牌完整数据集

MAJOR_ARCANA = [
    {"id": 0, "name": "愚者", "name_en": "The Fool", "keywords": "开始、天真、冒险、自由",
     "upright": "新的开始、天真烂漫、冒险精神、活在当下、无限可能",
     "reversed": "愚蠢、鲁莽、冒险过度、不负责任、缺乏判断力",
     "element": "风"},
    {"id": 1, "name": "魔术师", "name_en": "The Magician", "keywords": "创造、技能、自信、资源",
     "upright": "创造力、技能精湛、自信满满、资源齐备、心想事成",
     "reversed": "欺骗、能力不足、浪费天赋、操纵他人、缺乏方向",
     "element": "水"},
    {"id": 2, "name": "女祭司", "name_en": "The High Priestess", "keywords": "直觉、神秘、内在、智慧",
     "upright": "直觉敏锐、内在智慧、神秘力量、静待时机、潜意识",
     "reversed": "直觉受阻、隐藏信息、表面肤浅、焦虑不安、拒绝倾听内心",
     "element": "水"},
    {"id": 3, "name": "皇后", "name_en": "The Empress", "keywords": "丰饶、自然、母爱、美感",
     "upright": "丰饶丰收、母性光辉、自然之美、感官享受、创造力",
     "reversed": "依赖他人、创造力停滞、空虚失落、过度放纵、缺乏关怀",
     "element": "土"},
    {"id": 4, "name": "皇帝", "name_en": "The Emperor", "keywords": "权威、稳定、秩序、保护",
     "upright": "权威力量、结构稳定、领导能力、父爱保护、自律",
     "reversed": "专制独裁、过度控制、缺乏纪律、权力滥用、僵硬固执",
     "element": "火"},
    {"id": 5, "name": "教皇", "name_en": "The Hierophant", "keywords": "传统、信仰、教导、仪式",
     "upright": "传统价值、精神导师、教育学习、仪式感、团体归属",
     "reversed": "打破传统、过度保守、不服从教导、固执己见、墨守成规",
     "element": "土"},
    {"id": 6, "name": "恋人", "name_en": "The Lovers", "keywords": "爱情、选择、和谐、关系",
     "upright": "爱情降临、重要选择、和谐关系、价值观统一、吸引力",
     "reversed": "关系破裂、选择困难、价值观冲突、分离、失衡",
     "element": "风"},
    {"id": 7, "name": "战车", "name_en": "The Chariot", "keywords": "胜利、意志、决心、征服",
     "upright": "意志坚定、勇往直前、胜利在望、克服困难、自信满满",
     "reversed": "缺乏方向、意志薄弱、失败挫折、失控、鲁莽行事",
     "element": "水"},
    {"id": 8, "name": "力量", "name_en": "Strength", "keywords": "勇气、内在力量、耐心、同情",
     "upright": "内在力量、勇气可嘉、耐心坚持、温柔的力量、克服欲望",
     "reversed": "缺乏自信、软弱无力、自暴自弃、恐惧支配、情绪失控",
     "element": "火"},
    {"id": 9, "name": "隐士", "name_en": "The Hermit", "keywords": "内省、智慧、孤独、寻找",
     "upright": "内省沉思、寻求真理、独处充电、智慧导师、精神指引",
     "reversed": "孤立无援、过度孤独、逃避现实、拒绝帮助、迷失方向",
     "element": "土"},
    {"id": 10, "name": "命运之轮", "name_en": "Wheel of Fortune", "keywords": "变化、循环、命运、机遇",
     "upright": "命运转折、好运降临、人生循环、机遇来临、顺势而为",
     "reversed": "厄运连连、失去控制、抗拒变化、运气不佳、停滞不前",
     "element": "火"},
    {"id": 11, "name": "正义", "name_en": "Justice", "keywords": "公平、真相、法律、平衡",
     "upright": "公平公正、真相大白、法律裁决、因果报应、诚实正直",
     "reversed": "不公正、谎言欺骗、法律纠纷、逃避责任、失衡",
     "element": "风"},
    {"id": 12, "name": "倒吊人", "name_en": "The Hanged Man", "keywords": "牺牲、放下、新视角、等待",
     "upright": "心甘情愿的牺牲、换个角度看问题、暂停反思、灵性成长",
     "reversed": "拖延不前、无谓牺牲、抗拒放下、停滞、自我折磨",
     "element": "水"},
    {"id": 13, "name": "死神", "name_en": "Death", "keywords": "结束、转变、重生、释放",
     "upright": "结束旧阶段、彻底转变、重生契机、释放过去、不可阻挡",
     "reversed": "抗拒改变、停滞不前、恐惧新生、执着过去、衰而不死",
     "element": "水"},
    {"id": 14, "name": "节制", "name_en": "Temperance", "keywords": "平衡、适度、调和、耐心",
     "upright": "平衡和谐、适度原则、耐心调和、心灵平静、稳步前进",
     "reversed": "极端失衡、缺乏耐心、过度放纵、失调、急躁冲动",
     "element": "火"},
    {"id": 15, "name": "恶魔", "name_en": "The Devil", "keywords": "束缚、欲望、物质、依赖",
     "upright": "束缚成瘾、物质主义、欲望膨胀、陷入依赖、黑暗面",
     "reversed": "挣脱束缚、觉醒自由、克服成瘾、获得解放、直面恐惧",
     "element": "土"},
    {"id": 16, "name": "高塔", "name_en": "The Tower", "keywords": "剧变、崩塌、觉醒、启示",
     "upright": "突如其来的剧变、旧有崩塌、深刻觉醒、破而后立、真相爆发",
     "reversed": "灾难避免、抗拒变革、恐惧改变、因小失大、延误危机",
     "element": "火"},
    {"id": 17, "name": "星星", "name_en": "The Star", "keywords": "希望、灵感、宁静、指引",
     "upright": "希望之光、心灵宁静、灵感涌现、精神指引、疗愈愈合",
     "reversed": "失望沮丧、灵感枯竭、失去信仰、绝望无助、迷失方向",
     "element": "风"},
    {"id": 18, "name": "月亮", "name_en": "The Moon", "keywords": "幻觉、恐惧、潜意识、不确定",
     "upright": "梦境幻觉、潜意识浮现、恐惧不安、朦胧不清、直觉增强",
     "reversed": "释放恐惧、澄清误解、看清真相、克服焦虑、走出迷雾",
     "element": "水"},
    {"id": 19, "name": "太阳", "name_en": "The Sun", "keywords": "成功、快乐、活力、成就",
     "upright": "光明成功、快乐喜悦、活力四射、成就达成、自信闪耀",
     "reversed": "快乐受阻、小有挫折、缺乏热情、暂时的阴霾、自信不足",
     "element": "火"},
    {"id": 20, "name": "审判", "name_en": "Judgement", "keywords": "唤醒、重生、评估、宽恕",
     "upright": "内心觉醒、重新评估、获得宽恕、新生机遇、召唤使命",
     "reversed": "自我怀疑、拒绝觉醒、逃避审判、后悔莫及、原地踏步",
     "element": "火"},
    {"id": 21, "name": "世界", "name_en": "The World", "keywords": "完成、圆满、旅行、成就",
     "upright": "圆满完成、旅途终点、成就达成、和谐统一、世界视野",
     "reversed": "未竟之事、延迟到达、缺乏完成、原地踏步、不完整",
     "element": "土"}
]

# 小阿卡纳 - 权杖组
WANDS = [
    {"id": 101, "name": "权杖王牌", "name_en": "Ace of Wands", "keywords": "开始、灵感、新机会、创造力",
     "upright": "新的开始、创造灵感、充满热情、重大机遇、主动出击",
     "reversed": "延迟启动、缺乏动力、创意枯竭、犹豫不决、错失良机",
     "element": "火"},
    {"id": 102, "name": "权杖二", "name_en": "Two of Wands", "keywords": "规划、抉择、未来、野心",
     "upright": "未来规划、大胆抉择、广阔视野、远大抱负、迈出第一步",
     "reversed": "犹豫不决、缺乏规划、害怕改变、视野受限、退缩不前",
     "element": "火"},
    {"id": 103, "name": "权杖三", "name_en": "Three of Wands", "keywords": "远见、拓展、探索、前进",
     "upright": "远见卓识、事业拓展、探索未知、稳步前进、看好未来",
     "reversed": "进展缓慢、计划受阻、缺乏远见、障碍重重、需要耐心",
     "element": "火"},
    {"id": 104, "name": "权杖四", "name_en": "Four of Wands", "keywords": "庆祝、和谐、家园、成就",
     "upright": "庆祝成功、家庭和谐、安居乐业、阶段性成就、朋友欢聚",
     "reversed": "庆祝取消、家庭矛盾、缺乏稳定、内心不安、根基动摇",
     "element": "火"},
    {"id": 105, "name": "权杖五", "name_en": "Five of Wands", "keywords": "竞争、冲突、挑战、分歧",
     "upright": "激烈竞争、意见分歧、挑战重重、争强好胜、混乱局面",
     "reversed": "避免冲突、放弃竞争、和解协商、内部矛盾、重新合作",
     "element": "火"},
    {"id": 106, "name": "权杖六", "name_en": "Six of Wands", "keywords": "胜利、认可、荣耀、自信",
     "upright": "取得胜利、获得认可、荣耀时刻、自信高涨、众人拥戴",
     "reversed": "失败跌倒、缺乏认可、骄傲自满、声誉受损、期待落空",
     "element": "火"},
    {"id": 107, "name": "权杖七", "name_en": "Seven of Wands", "keywords": "坚守、防御、挑战、勇气",
     "upright": "坚守阵地、勇敢面对、捍卫立场、克服挑战、不屈不挠",
     "reversed": "力不从心、放弃抵抗、处于劣势、被压倒、疲惫不堪",
     "element": "火"},
    {"id": 108, "name": "权杖八", "name_en": "Eight of Wands", "keywords": "迅速、行动、沟通、进展",
     "upright": "迅速发展、行动迅速、好消息传来、沟通顺畅、势如破竹",
     "reversed": "延迟延误、沟通受阻、进展缓慢、计划暂停、等待时机",
     "element": "火"},
    {"id": 109, "name": "权杖九", "name_en": "Nine of Wands", "keywords": "坚韧、坚持、警惕、边界",
     "upright": "坚韧不拔、最后防线、保持警惕、设立边界、不屈精神",
     "reversed": "筋疲力尽、放弃抵抗、过度防御、偏执多疑、孤立无援",
     "element": "火"},
    {"id": 110, "name": "权杖十", "name_en": "Ten of Wands", "keywords": "负担、压力、责任、坚持",
     "upright": "负担沉重、压力山大、承担过多责任、咬牙坚持、过度付出",
     "reversed": "卸下重担、放手减压、拒绝过度责任、寻求帮助、学会说不",
     "element": "火"},
    {"id": 111, "name": "权杖侍从", "name_en": "Page of Wands", "keywords": "探索、热情、冒险、消息",
     "upright": "充满热情、探索精神、冒险尝试、好消息传来、新身份",
     "reversed": "缺乏方向、热情消退、拖延不前、不成熟、消息延误",
     "element": "火"},
    {"id": 112, "name": "权杖骑士", "name_en": "Knight of Wands", "keywords": "行动、冒险、冲动、能量",
     "upright": "行动力强、冒险精神、充满能量、直奔目标、勇往直前",
     "reversed": "冲动行事、半途而废、鲁莽冒进、缺乏耐心、能量耗尽",
     "element": "火"},
    {"id": 113, "name": "权杖王后", "name_en": "Queen of Wands", "keywords": "自信、热情、果断、温暖",
     "upright": "自信满满、热情洋溢、果断决策、温暖感染力、领导魅力",
     "reversed": "嫉妒自私、缺乏自信、情绪化、专横跋扈、内心不安",
     "element": "火"},
    {"id": 114, "name": "权杖国王", "name_en": "King of Wands", "keywords": "领袖、远见、创业、魄力",
     "upright": "天生领袖、远见卓识、创业精神、魄力非凡、成熟稳重",
     "reversed": "专横傲慢、要求过高、缺乏远见、令人畏惧、滥用权力",
     "element": "火"}
]

# 小阿卡纳 - 圣杯组
CUPS = [
    {"id": 201, "name": "圣杯王牌", "name_en": "Ace of Cups", "keywords": "爱、情感、开启、直觉",
     "upright": "爱情的开启、情感充沛、直觉敏锐、新的感受、心灵满足",
     "reversed": "情感封闭、爱意受阻、直觉迟钝、内心空虚、情感压抑",
     "element": "水"},
    {"id": 202, "name": "圣杯二", "name_en": "Two of Cups", "keywords": "结合、吸引力、平等、友谊",
     "upright": "恋人结合、强烈吸引力、平等关系、深厚友谊、合作和谐",
     "reversed": "关系失衡、分手分离、吸引力消退、友谊破裂、相互误解",
     "element": "水"},
    {"id": 203, "name": "圣杯三", "name_en": "Three of Cups", "keywords": "庆祝、友谊、喜悦、聚会",
     "upright": "欢庆聚会、真挚友谊、喜悦分享、姐妹情深、感恩祝福",
     "reversed": "过度放纵、友谊变质、孤单寂寞、庆祝取消、八卦流言",
     "element": "水"},
    {"id": 204, "name": "圣杯四", "name_en": "Four of Cups", "keywords": "沉思、不满足、冥想、机会",
     "upright": "沉思内省、对现状不满、麻木不仁、新的机会被忽视",
     "reversed": "重新振作、抓住机会、走出抑郁、觉醒行动、迎接改变",
     "element": "水"},
    {"id": 205, "name": "圣杯五", "name_en": "Five of Cups", "keywords": "失落、悲伤、遗憾、失望",
     "upright": "失落悲伤、沉浸遗憾、过度关注失去、失望难过、悲痛",
     "reversed": "接受过去、走出悲伤、重整旗鼓、看到希望、宽恕释怀",
     "element": "水"},
    {"id": 206, "name": "圣杯六", "name_en": "Six of Cups", "keywords": "回忆、怀旧、天真、赠予",
     "upright": "美好回忆、怀旧之情、天真单纯、慷慨赠予、重逢喜悦",
     "reversed": "困于过去、无法向前、不切实际、停滞不前、回忆阻塞",
     "element": "水"},
    {"id": 207, "name": "圣杯七", "name_en": "Seven of Cups", "keywords": "幻想、选择、白日梦、诱惑",
     "upright": "众多选择、幻想诱惑、白日做梦、难以抉择、欲望投射",
     "reversed": "清醒现实、聚焦目标、做出选择、落地执行、摆脱幻想",
     "element": "水"},
    {"id": 208, "name": "圣杯八", "name_en": "Eight of Cups", "keywords": "放手、离开、寻找、转变",
     "upright": "主动放手、离开旧境、追寻意义、情感转变、勇敢告别",
     "reversed": "害怕离开、固守不满、迷失方向、徒劳追寻、迟疑不决",
     "element": "水"},
    {"id": 209, "name": "圣杯九", "name_en": "Nine of Cups", "keywords": "满足、愿望、舒适、幸福",
     "upright": "愿望成真、内心满足、舒适愉悦、幸福美满、心想事成",
     "reversed": "愿望落空、表面风光内心空虚、不满现状、贪得无厌",
     "element": "水"},
    {"id": 210, "name": "圣杯十", "name_en": "Ten of Cups", "keywords": "幸福、家庭、圆满、和谐",
     "upright": "家庭幸福、情感圆满、和谐美满、人间天堂、持久幸福",
     "reversed": "家庭破碎、梦想破灭、情感不和谐、表面和谐、被破坏的白日梦",
     "element": "水"},
    {"id": 211, "name": "圣杯侍从", "name_en": "Page of Cups", "keywords": "灵感、直觉、好奇、消息",
     "upright": "灵感涌现、直觉增强、好奇心强、情感消息、创意开启",
     "reversed": "情感不成熟、创意受阻、逃避感受、幼稚幻想、消息延迟",
     "element": "水"},
    {"id": 212, "name": "圣杯骑士", "name_en": "Knight of Cups", "keywords": "追求、浪漫、理想、邀请",
     "upright": "浪漫追求、理想主义、富有魅力、邀请到来、追随内心",
     "reversed": "情感欺骗、不切实际、过度理想化、嫉妒吃醋、失望",
     "element": "水"},
    {"id": 213, "name": "圣杯王后", "name_en": "Queen of Cups", "keywords": "关怀、直觉、治愈、温暖",
     "upright": "温柔关怀、直觉敏锐、治愈能力、善解人意、情感丰富",
     "reversed": "情感过度、过度敏感、自我牺牲、情绪泛滥、被忽略",
     "element": "水"},
    {"id": 214, "name": "圣杯国王", "name_en": "King of Cups", "keywords": "成熟、慈悲、稳定、智慧",
     "upright": "情感成熟、慈悲为怀、情绪稳定、智慧包容、温和领导",
     "reversed": "情绪压抑、情感操纵、双面人格、内心混乱、冷漠疏离",
     "element": "水"}
]

# 小阿卡纳 - 宝剑组
SWORDS = [
    {"id": 301, "name": "宝剑王牌", "name_en": "Ace of Swords", "keywords": "真理、清晰、决心、突破",
     "upright": "真理浮现、思路清晰、重大突破、决心坚定、新想法",
     "reversed": "混淆混乱、错误判断、沟通不畅、思路阻塞、缺乏方向",
     "element": "风"},
    {"id": 302, "name": "宝剑二", "name_en": "Two of Swords", "keywords": "抉择、僵局、回避、平衡",
     "upright": "难以抉择、陷入僵局、逃避现实、需要平衡、内心矛盾",
     "reversed": "无法逃避、信息过载、做出决定、打破僵局、直面问题",
     "element": "风"},
    {"id": 303, "name": "宝剑三", "name_en": "Three of Swords", "keywords": "伤心、痛苦、心痛、真相",
     "upright": "心痛悲伤、感情伤害、痛苦真相、背叛打击、泪水",
     "reversed": "走出伤痛、释放痛苦、修复创伤、接受现实、伤口愈合",
     "element": "风"},
    {"id": 304, "name": "宝剑四", "name_en": "Four of Swords", "keywords": "休息、恢复、冥想、静养",
     "upright": "休养生息、冥想充电、暂时撤退、恢复能量、静待时机",
     "reversed": "拒绝休息、疲惫不堪、无法平静、过早行动、倦怠耗尽",
     "element": "风"},
    {"id": 305, "name": "宝剑五", "name_en": "Five of Swords", "keywords": "冲突、失败、屈辱、损失",
     "upright": "冲突争执、惨胜如败、屈辱退让、损失惨重、人际对立",
     "reversed": "和解修复、放下争执、接受失败、避免无谓冲突、吸取教训",
     "element": "风"},
    {"id": 306, "name": "宝剑六", "name_en": "Six of Swords", "keywords": "过渡、放下、前行、宁静",
     "upright": "过渡时期、放下过去、走向更好、平静前行、心灵之旅",
     "reversed": "无法放下、困于过去、旅程受阻、抗拒改变、延迟过渡",
     "element": "风"},
    {"id": 307, "name": "宝剑七", "name_en": "Seven of Swords", "keywords": "策略、欺骗、秘密、计划",
     "upright": "灵活策略、智取巧胜、保密计划、独辟蹊径、善于变通",
     "reversed": "谎言败露、自欺欺人、偷鸡不成、策略失误、诚实面对",
     "element": "风"},
    {"id": 308, "name": "宝剑八", "name_en": "Eight of Swords", "keywords": "束缚、困境、无助、自我限制",
     "upright": "感觉被困、自我设限、无助无望、消极思维、视野狭窄",
     "reversed": "挣脱束缚、自我解放、找到出路、新的视角、拒绝受害者心态",
     "element": "风"},
    {"id": 309, "name": "宝剑九", "name_en": "Nine of Swords", "keywords": "焦虑、噩梦、恐惧、担忧",
     "upright": "深夜焦虑、噩梦缠身、过度担忧、恐惧失眠、精神压力",
     "reversed": "克服恐惧、放下焦虑、寻求帮助、内心释然、恢复安宁",
     "element": "风"},
    {"id": 310, "name": "宝剑十", "name_en": "Ten of Swords", "keywords": "终结、失败、痛苦、重生",
     "upright": "痛苦终结、跌入谷底、彻底结束、背叛伤害、黑暗尽头",
     "reversed": "否极泰来、浴火重生、学习教训、缓慢恢复、拒绝结束",
     "element": "风"},
    {"id": 311, "name": "宝剑侍从", "name_en": "Page of Swords", "keywords": "好奇、沟通、警觉、新思",
     "upright": "好奇心强、思维敏捷、善于沟通、警觉观察、新想法",
     "reversed": "言辞伤人、过度批判、沟通不畅、思维混乱、轻率决定",
     "element": "风"},
    {"id": 312, "name": "宝剑骑士", "name_en": "Knight of Swords", "keywords": "行动、速决、直言、冲刺",
     "upright": "果断行动、直截了当、快速推进、言辞犀利、勇往直前",
     "reversed": "冲动鲁莽、不顾后果、言语伤人、半途而废、急躁冒进",
     "element": "风"},
    {"id": 313, "name": "宝剑王后", "name_en": "Queen of Swords", "keywords": "清晰、独立、洞察、边界",
     "upright": "思维清晰、独立自主、洞察力强、设立边界、表达真我",
     "reversed": "刻薄冷漠、过度批判、孤独封闭、钻牛角尖、拒人千里",
     "element": "风"},
    {"id": 314, "name": "宝剑国王", "name_en": "King of Swords", "keywords": "理性、权威、公正、战略",
     "upright": "理性分析、权威专业、公正无私、战略眼光、智慧决策",
     "reversed": "专横判断、滥用权力、冷血无情、不公不义、情绪压制理智",
     "element": "风"}
]

# 小阿卡纳 - 星币组
PENTACLES = [
    {"id": 401, "name": "星币王牌", "name_en": "Ace of Pentacles", "keywords": "开始、财富、机会、物质",
     "upright": "财富新机、物质开始、理财良机、落地生根、务实启动",
     "reversed": "错失良机、财务失利、计划延迟、缺乏资源、不稳定",
     "element": "土"},
    {"id": 402, "name": "星币二", "name_en": "Two of Pentacles", "keywords": "平衡、适应、多任务、变化",
     "upright": "平衡收支、适应变化、多任务处理、灵活变通、时间管理",
     "reversed": "不堪重负、财务失衡、手忙脚乱、失去平衡、过度消费",
     "element": "土"},
    {"id": 403, "name": "星币三", "name_en": "Three of Pentacles", "keywords": "协作、技能、团队、学习",
     "upright": "团队协作、技能提升、精益求精、共同目标、学徒阶段",
     "reversed": "缺乏合作、技能不足、质量粗糙、团队不和、忽视细节",
     "element": "土"},
    {"id": 404, "name": "星币四", "name_en": "Four of Pentacles", "keywords": "守财、保守、控制、安全",
     "upright": "节俭储蓄、保守理财、掌控资源、寻求安全、守住已有",
     "reversed": "过度吝啬、挥霍无度、财务失控、害怕失去、固步自封",
     "element": "土"},
    {"id": 405, "name": "星币五", "name_en": "Five of Pentacles", "keywords": "匮乏、困难、孤独、精神",
     "upright": "物质匮乏、经济困难、感到被排斥、健康问题、精神寒冬",
     "reversed": "走出困境、获得帮助、恢复富足、重拾信心、找到归属",
     "element": "土"},
    {"id": 406, "name": "星币六", "name_en": "Six of Pentacles", "keywords": "慷慨、分享、捐赠、公平",
     "upright": "慷慨解囊、公平分配、施与受、帮助他人、感恩回报",
     "reversed": "条件交换、不公平、债务压力、吝啬小气、依赖他人",
     "element": "土"},
    {"id": 407, "name": "星币七", "name_en": "Seven of Pentacles", "keywords": "耐心、评估、投资、等待",
     "upright": "耐心等待回报、评估进展、长期投资、耕耘收获、反思",
     "reversed": "收成不佳、投资损失、缺乏耐心、半途而废、徒劳无功",
     "element": "土"},
    {"id": 408, "name": "星币八", "name_en": "Eight of Pentacles", "keywords": "工匠、专注、技能、勤奋",
     "upright": "专注工作、精进技能、勤奋练习、追求卓越、学以致用",
     "reversed": "敷衍了事、缺乏动力、技能停滞、工作无趣、追求捷径",
     "element": "土"},
    {"id": 409, "name": "星币九", "name_en": "Nine of Pentacles", "keywords": "富足、自律、独立、优雅",
     "upright": "丰硕成果、自律成就、独立自主、优雅生活、物质稳定",
     "reversed": "表面风光、依赖他人、财务不稳、过度奢侈、失去独立性",
     "element": "土"},
    {"id": 410, "name": "星币十", "name_en": "Ten of Pentacles", "keywords": "传承、财富、家族、长久",
     "upright": "世代传承、家族财富、长久基业、祖荫庇护、物质丰盛",
     "reversed": "家族矛盾、破败衰落、遗产纠纷、失去传承、财务危机",
     "element": "土"},
    {"id": 411, "name": "星币侍从", "name_en": "Page of Pentacles", "keywords": "学习、实践、目标、勤勉",
     "upright": "务实学习、脚踏实地、设定目标、勤勉努力、新技能",
     "reversed": "缺乏规划、拖延怠惰、目标模糊、不切实际、半途而废",
     "element": "土"},
    {"id": 412, "name": "星币骑士", "name_en": "Knight of Pentacles", "keywords": "勤奋、可靠、耐心、责任",
     "upright": "勤奋工作、可靠稳妥、耐心坚持、承担责任、稳扎稳打",
     "reversed": "懒惰怠工、固执僵化、无聊乏味、缺乏冒险、停滞不前",
     "element": "土"},
    {"id": 413, "name": "星币王后", "name_en": "Queen of Pentacles", "keywords": "务实、滋养、舒适、慷慨",
     "upright": "务实能干、滋养关怀、舒适生活、慷慨大方、理财能手",
     "reversed": "忽视家庭、财务焦虑、过度物质、缺乏关怀、不安全感",
     "element": "土"},
    {"id": 414, "name": "星币国王", "name_en": "King of Pentacles", "keywords": "富足、成功、商业、稳健",
     "upright": "财富自由、商业成功、稳健可靠、成熟稳重、富足智慧",
     "reversed": "贪婪无度、财务腐败、固执守旧、过度物质、管理不善",
     "element": "土"}
]

ALL_CARDS = MAJOR_ARCANA + WANDS + CUPS + SWORDS + PENTACLES

def get_all_cards():
    """返回所有78张塔罗牌"""
    return ALL_CARDS

def get_card_by_id(card_id):
    """根据ID查找牌"""
    for card in ALL_CARDS:
        if card["id"] == card_id:
            return card
    return None

def get_card_name(card_id):
    """根据ID获取牌名"""
    card = get_card_by_id(card_id)
    return card["name"] if card else "未知"
